activation_function: tanh
add_weight: 0.0
batch_size: 10000
batch_size_testing: 10000
dataloader_num_workers: 8
dataset_path: /home/alex/torch_datasets/AMPCPendulumNew15
early_stopping_patience: 1000
evaluation_size: 0.1
hpc_data_path: /home/alex/hpc_data/pendulum_swingupNew15
learning_rate: 0.01
max_epochs: 3000
num_aug_params: 5
num_layers: 8
num_neurons: 50
num_sys_inputs: 1
num_sys_states: 4
seed: 1
test_size: 0.0
train_aug: false
train_size: 0.9
